#.travis.yml

language: node_js
node_js:
  - "node"
cache:
  - npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - cd functions && npm install

script:
  - npm run lint
  - npm run build
  - cd ..
  - ng lint
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng build pp-pigpen --configuration=production --aot
  - npm start & wait-on http://localhost:8080
  - cypress run

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "O8F6FqkA7kywQus2M1DoBmA+nzNEId2eJj0Ype3SX8F4jzLZfeCcZe5PPWPwd0RwtJpHsH17fzgcexDHCae9boXJ7oDPrp3uCunPyc1CKtt/Tu+k0AoOvN0vnj3vJTxubmdDZaLUDCwsdcNM754S2doTo+0ho+2VgFuNh81ZzTHvzgeCpFe/Opsba6sio1V3JFqqP227HOEukVygjcJSzam/ux8a4yVS0gH/5DEmJjVdyid9CWTjye62PLHg2IfXHeWqAvxxkiYMB753oKgYoVoPMcn26V/51jgsdtQg70eTbr1k2KILxY1gu1unMNPQcZsoiEZUl6LGw6zpTSODndvQHl5b3RXBaR+xpuTdgNMnpg9rxS1Entzcg9khb4qYRkUEjXi86mzzhvqe7A6nkWa9JAi6jhxh/PfZrViUWd7KjwcSKwKVZLXH+g2y/tayrVpvIr0fAO2uPbFMwTO+HeCFwdxUGT1eNMOHKeQQS8enCC0VyMBhhcG8GS3254F53hJ+UxYnfKQ75e+qzZlxFKh6yKO8vRhqLZCnk3SkzrzOrWZPAmOXAA3ewN3MU+YhU+d4LK3u91JsKxN5/SANACDUCVMpBB1I8wqN37DBHvCOWayeMOlYKBqVc/D3DBmX5A34nuwGvZNT9pTsgcpcmvyIjN7Bj/u7H0AeMFozMgg="


