#.travis.yml

language: node_js
node_js:
  - "node"
cache:
  - npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - sed -ri "s/TRAVIS_BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/" src/environments/version.ts
  - sed -ri "s/TRAVIS_COMMIT/$TRAVIS_COMMIT/" src/environments/version.ts
  - npm install -g @angular/cli
#  - npm install @sentry/cli
  - npm install -g wait-on
  - cd functions && npm install

script:
  - npm run lint
  - npm run build
  - cd ..
  - ng lint
  - ng build pp-pigpen --configuration=production --aot
  - npm start & wait-on http-get://localhost:4200
  - cypress run --browser chromium

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: firebase
  skip_cleanup: true

#Don't think we need this with public source maps?
#after_deploy:
#  -  sentry-cli releases files #TRAVIS_BUILD_NUMBER upload-sourcemaps --ext ts --ext map /path/to/files

notifications:
  webhooks:
  - https://us-central1-pp-pigpen.cloudfunctions.net/apiTravisDeploy
  - https://sentry.io/api/hooks/release/builtin/1422082/202a0f527a776b2787ce1109a32bd90a88d0880678ede18cfc1ca0291d52cd91/


